### ISSUE TITLE
Buttons not been read

### ISSUE THREAD

**Issue by OneGoogus** [Baldhor/Homey-ESPhome-Enhanced#1]
Hi Baldhor

Could you assist me on why current high and buttons are not loaded in Homey?

in the yaml for my device I have sensor, which your app reads perfectly, but then I have numbers and buttons which are not displayed in the app. but when I add to Home Assistent, it adds them without any problems.

How do I progress?

`
uart:
  id: uart_desk
  baud_rate: 115200
  tx_pin: D0
  rx_pin: D1

sensor:
  - platform: custom
    lambda: |-
      auto megadesk = new Megadesk(id(uart_desk));
      App.register_component(megadesk);
      return { megadesk->raw_height, megadesk->min_height, megadesk->max_height };
    sensors:
    - id: megadesk_raw
      internal: true
      on_value:
        then:
          - component.update: megadesk_height_inches
          - component.update: megadesk_height_cm
          - component.update: megadesk_height_raw
    - name: "Megadesk Minimum Height"
    - name: "Megadesk Maximum Height"

number:
  - platform: template
    name: "Megadesk Height (inches)"
    id: megadesk_height_inches
    min_value: 23
    max_value: 47
    step: 0.53
    mode: slider
    update_interval: never
    unit_of_measurement: 'inches'
    #NewValue = (((OldValue - OldMin) * (NewMax - NewMin)) / (OldMax - OldMin)) + NewMin
    lambda: |-
      return ((((id(megadesk_raw).state - 299) * (47 - 23)) / (6914 - 299)) + 23);
    set_action:
      - number.set:
          id: megadesk_height_raw
          value: !lambda "return int((((x - 23) * (6914 - 299)) / (47 - 23)) + 299);"
  - platform: template
    name: "Megadesk Height (cm)"
    id: megadesk_height_cm
    min_value: 58.42
    max_value: 118.745
    step: 0.53
    mode: slider
    update_interval: never
    unit_of_measurement: 'cm'
    #NewValue = (((OldValue - OldMin) * (NewMax - NewMin)) / (OldMax - OldMin)) + NewMin
    lambda: |-
      return ((((id(megadesk_raw).state - 299) * (119.38 - 58.42)) / (6914 - 299)) + 58.42);
    set_action:
      - number.set:
          id: megadesk_height_raw
          value: !lambda "return int((((x - 58.42) * (6640 - 299)) / (119.38 - 58.42)) + 299);"
  - platform: template
    name: "Megadesk Height (raw)"
    id: megadesk_height_raw
#    internal: true
    min_value: 299
    max_value: 6640
    step: 1
    mode: slider
    update_interval: never
    lambda: |-
      return id(megadesk_raw).state;
    set_action:
      - uart.write: !lambda |-
          char buf[20];
          sprintf(buf, "<=%i,.", int(x));
          std::string s = buf;
          return std::vector<unsigned char>( s.begin(), s.end() );

button:
  - platform: template
    name: "Desk Position 2"
    on_press:
      then:
        - uart.write: "<L0,2."
  - platform: template
    name: "Desk Position 3"
    on_press:
      then:
        - uart.write: "<L0,3."
  - platform: template
    name: "Desk Position 4"
    on_press:
      then:
        - uart.write: "<L0,4."
  - platform: template
    name: "Desk Position 5"
    on_press:
      then:
        - uart.write: "<L0,5."
  - platform: template
    name: "Toggle Minimum Desk Height"
    on_press:
      then:
        - uart.write: "<L0,11."
        - uart.write: "<R0,11."
  - platform: template
    name: "Toggle Maximum Desk Height"
    on_press:
      then:
        - uart.write: "<L0,12."
        - uart.write: "<R0,12."
  - platform: template
    name: "Recalibrate Desk"
    on_press:
      then:
        - uart.write: "<L0,14."
  - platform: template
    name: "Reboot Megadesk"
    on_press:
      then:
        - uart.write: "<L0,15."
  - platform: template
    name: "Toggle Audio feedback"
    on_press:
      then:
        - uart.write: "<L0,17."
  - platform: template
    name: "Toggle both-button mode"
    on_press:
      then:
        - uart.write: "<L0,18."
`

**Comment by Baldhor** [comment]
@OneGoogus The app supports switch, sensor and cover for now. I do not have "press button", but I think I could add it within minutes if I have enough information on their behaviours.
The problem is how to collect those information ... I'm trying to add console.re support to the app to make it easier, but I still have lot of work on it.

In the meantime the only solution would be for you to install the app from the command line, so you can collect the logs.
Would you be able to do so ?

I made a wiki page quickly, hopefully it will help!
https://github.com/Baldhor/Homey-ESPhome-Enhanced/wiki/How-to-run-the-app-from-command-line

**Comment by Baldhor** [comment]
@OneGoogus I added support for button in a test version: https://homey.app/fr-fr/app/nl.inversion.esphome/ESPhome/test/

I have good hope about it, but I cannot test it myself.

**Note 1:** the button in homey doesn't update when you press it on the device! Because it is considered "too fast". However, if you press it on homey side, it should send the command to the device!
I think it's the behaviour  you expect!

**Note 2:** During pairing, the entity will not appear in the list (only measure appear in the list), same as switch and cover. However, the capability should be added to the device, and the cars (flow, action, ...) should be available!


Happy testing, and please let us know if it works!

**Comment by OneGoogus** [comment]
Hi Baldhor.

Sorry I did not see the previous post.
But it seems your changes worked. All buttons works just like a toggle, desk moving to the saved positions, reboot, recalibrating and settings of new max and min height settings works like a charm.
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/2384481/f565700b-8b3f-404f-aab1-73a3e4672193)

The only thing missing is the number in the yaml, which in Home Assistant is a slider. So im not sure how to progress that in Homey.

![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/2384481/4f32b2d7-b3e8-4df7-974a-2e20603bb70d)

**Comment by Baldhor** [comment]
@OneGoogus You are talking about the slider ? It would be another type of capability I think. Like a dimmer.

If at least it's ok for the button, I can publish officially version 0.3.1.
=> Please confirm!

As for the dimmer, let's open another enhancement request :)
=> I will need your yaml configuration and logs :)

**Comment by OneGoogus** [comment]
Confirmed. I open up another request for the slider / dimmer.

**Comment by Baldhor** [comment]
@OneGoogus There are some bugs on Homey side currently, but I think 0.3.1 is now live. Please post a comment in homey store to give more visibility to the app :)
