### ISSUE TITLE
Update of the accuracy_decimals on device connection

### ISSUE THREAD

**Issue by Baldhor** [Baldhor/Homey-ESPhome-Enhanced#4]
**Is your feature request related to a problem? Please describe.**
Related to issue #2, the accuracy_decimals is only setup at pairing stage, but device configuration could change over time.
It could be great to be able to dynamically update the configuration.

**Describe the solution you'd like**
Update of the capability option in Homey based on device configuration.

**Describe alternatives you've considered**
Alternatively, the device setting page could allow overwritting of the device setting.
Note: it could be additive.

**Additional context**
none

**Comment by aedens78** [comment]
Not sure if related, but the amount of decimal places seems to be ignored entirely?

According to the log on my ESPHome/slimmelezer it is reporting these values with these decimals of accuracy:

```
13:47:53	[D]	[sensor:093]	'Power Consumed Phase 1': Sending state 0.48100 kW with 3 decimals of accuracy
13:47:53	[D]	[sensor:093]	'Energy Consumed Tariff 1': Sending state 3375.22803 kWh with 3 decimals of accuracy
13:47:53	[D]	[sensor:093]	'Energy Consumed Tariff 2': Sending state 3789.25708 kWh with 3 decimals of accuracy
```
However, in the Homey web app (in the browser) there are less decimals:
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/95985847/a04eed2b-f072-4683-b84b-df86265374c3)
(Only 2 instead of the 3 it should display?)

And the iPhone app is even more confused:
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/95985847/31a7c0c1-ccad-4151-8786-19ed423ddd29)
(I'm not even going to count the amount of decimals there)

I have nothing specific set in the ESPHome config about the decimals; This is how I set the device up on the Homey:
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/95985847/92f7b64a-fe22-4b32-b7ff-777143faa8bf)

(The screenshots and the log snippet were taken at different moments, therefore the actual values don't match)

**Comment by Baldhor** [comment]
@aedens78 Thanks for all those details, you are right, it is obviously ignored!
I should have enough information (thx to your screenshots) to look at it.

However, it's an obvious bug, and not directly related to the enhancement proposed here, I will separate the 2 subjects :)

**Comment by Baldhor** [comment]
refer to : https://github.com/Baldhor/Homey-ESPhome-Enhanced/issues/12#issuecomment-1680879637
The wizard allows to modify the options of a capability!

@aedens78 You could be interrested :)
